spring:
  cloud:
    gateway:
      routes:
      - id: message-service
        uri: lb://message-service
        predicates:
        - Path=/billboard/**
        filters:
        - StripPrefix=1

      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: false
